// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 마이그레이션(DDL)은 pgbouncer를 거치지 않는 direct 연결을 사용한다.
    // Neon: DATABASE_URL_UNPOOLED(=-pooler 없는 호스트). 로컬엔 없으므로 DATABASE_URL로 폴백.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
