// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 마이그레이션(DDL)은 Transaction pooler(pgbouncer)를 거치지 않는 연결을 써야 한다.
    // Supabase: DATABASE_URL_UNPOOLED(=Session pooler 5432). 없으면 DATABASE_URL로 폴백.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
